# .github/workflows/ci.yml
name: Java CI Pipeline

on:
  push:
    branches:
      - main  
      - master # Trigger pipeline on push to the main branch
  pull_request:
    branches:
      - main   # Trigger pipeline on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'          # Use Java 17 (or change as per your requirement)
          distribution: 'temurin'     # Use the Temurin distribution of OpenJDK

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project
      - name: Build with Maven
        run: mvn clean install

      # Run tests
      - name: Run tests
        run: mvn test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Artifact
        run: |
          echo "Deploying the artifact..."
          # Add your deployment script/commands here
          # Example: scp, upload to S3, or deploy to a cloud provider
